package com.group5.paul_esys.screens.registrar.enroll_user;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTGitHubIJTheme;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 * @author janea
 */
public class StudentEnrollmentForm extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger =
    java.util.logging.Logger.getLogger(StudentEnrollmentForm.class.getName());

  /**
   * Creates new form Enrollment
   */
  public StudentEnrollmentForm() {
    FlatMTGitHubIJTheme.setup();
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                txtFirstName = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                txtEmail = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                btnClose = new javax.swing.JButton();
                btnRegister = new javax.swing.JButton();
                jComboBox1 = new javax.swing.JComboBox<>();
                windowBar1 = new com.group5.paul_esys.components.WindowBar();
                txtConfirmPassword = new javax.swing.JPasswordField();
                txtPassword = new javax.swing.JPasswordField();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                cbxDepartment = new javax.swing.JComboBox<>();
                cbxCurriculum = new javax.swing.JComboBox<>();
                cbxCurriculum1 = new javax.swing.JComboBox<>();
                txtLastName = new javax.swing.JTextField();
                jLabel13 = new javax.swing.JLabel();
                txtMiddleName = new javax.swing.JTextField();
                jLabel14 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                jLabel1.setText("VINCE BATECAN STATE ");
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

                jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                jLabel2.setText("UNIVERSITY");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

                jLabel3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel3.setText("Create a new student account ");
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

                jLabel5.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel5.setText("First Name");
                jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

                txtFirstName.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
                txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtFirstNameKeyReleased(evt);
                        }
                });
                jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, -1));

                jLabel6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel6.setText("Email Address (For Student Portal)");
                jLabel6.setToolTipText("An email address that will be created for this student.");
                jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 330, -1));

                txtEmail.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
                jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 330, -1));

                jLabel7.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel7.setText("Confirm Password");
                jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

                jLabel8.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel8.setText("Student Type");
                jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

                jLabel9.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel9.setText("Program/Course");
                jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

                jLabel10.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel10.setText("Password");
                jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

                btnClose.setBackground(new java.awt.Color(255, 234, 234));
                btnClose.setText("Cancel");
                btnClose.addActionListener(this::btnCloseActionPerformed);
                jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 150, -1));

                btnRegister.setBackground(new java.awt.Color(255, 234, 234));
                btnRegister.setText("Register");
                btnRegister.setEnabled(false);
                btnRegister.addActionListener(this::btnRegisterActionPerformed);
                jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 150, -1));

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULAR", "IRREGULAR" }));
                jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 330, -1));
                jPanel1.add(windowBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, -1));

                txtConfirmPassword.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
                txtConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                txtConfirmPasswordKeyPressed(evt);
                        }
                });
                jPanel1.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 150, -1));

                txtPassword.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
                jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 150, -1));

                jLabel11.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel11.setText("Curriculum");
                jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

                jLabel12.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel12.setText("Department");
                jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

                cbxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "College of Engineering" }));
                jPanel1.add(cbxDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 330, -1));

                cbxCurriculum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Information Technology" }));
                jPanel1.add(cbxCurriculum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 330, -1));

                cbxCurriculum1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT2023" }));
                jPanel1.add(cbxCurriculum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, -1));

                txtLastName.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
                txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtLastNameKeyReleased(evt);
                        }
                });
                jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 330, -1));

                jLabel13.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel13.setText("Last Name");
                jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

                txtMiddleName.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
                jPanel1.add(txtMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));

                jLabel14.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jLabel14.setText("Middle Name (Optional)");
                jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

  private void buildStudentEmail() {
    // Sa format na lastname.firstname@paul.edu.ph. Sometimes, yung first name may spaces
    String firstName = txtFirstName
      .getText()
      .trim()
      .toLowerCase()
      .replace(" ", "");
    String lastName = txtLastName.getText().trim().toLowerCase();
    String email = lastName + "." + firstName + "@paul.edu.ph";
    txtEmail.setText(email);
  }

  private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnCloseActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnCloseActionPerformed

  private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_btnRegisterActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnRegisterActionPerformed

  private void txtConfirmPasswordKeyPressed(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_txtConfirmPasswordKeyPressed
    String password = new String(txtPassword.getPassword());
    String confirmPassword = new String(txtConfirmPassword.getPassword());

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(
          null,
          "Password do not match!",
          "Error",
          JOptionPane.ERROR_MESSAGE
        );
        txtConfirmPassword.requestFocus();
      } else {
        btnRegister.doClick();
      }
    }
  }//GEN-LAST:event_txtConfirmPasswordKeyPressed

  private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_txtFirstNameKeyReleased
    buildStudentEmail();
  }//GEN-LAST:event_txtFirstNameKeyReleased

  private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_txtLastNameKeyReleased
    buildStudentEmail();
  }//GEN-LAST:event_txtLastNameKeyReleased

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() ->
      new StudentEnrollmentForm().setVisible(true)
    );
  }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnClose;
        private javax.swing.JButton btnRegister;
        private javax.swing.JComboBox<String> cbxCurriculum;
        private javax.swing.JComboBox<String> cbxCurriculum1;
        private javax.swing.JComboBox<String> cbxDepartment;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPasswordField txtConfirmPassword;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtFirstName;
        private javax.swing.JTextField txtLastName;
        private javax.swing.JTextField txtMiddleName;
        private javax.swing.JPasswordField txtPassword;
        private com.group5.paul_esys.components.WindowBar windowBar1;
        // End of variables declaration//GEN-END:variables
}
