package com.group5.paul_esys.screens.sign_in;

import com.formdev.flatlaf.FlatLightLaf;
import com.group5.paul_esys.modules.users.models.user.LoginData;
import com.group5.paul_esys.modules.users.models.user.UserInformation;
import com.group5.paul_esys.modules.users.services.AuthService;
import com.group5.paul_esys.modules.users.services.UserSession;
import com.group5.paul_esys.screens.admin.AdminDashboard;
import com.group5.paul_esys.screens.faculty.FacultyDashboard;
import com.group5.paul_esys.screens.registrar.RegistrarDashboard;
import com.group5.paul_esys.screens.student.StudentDashboard;
import java.awt.event.KeyEvent;
import java.util.Optional;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author janea
 */
public class SignIn extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger =
    java.util.logging.Logger.getLogger(SignIn.class.getName());
  private final AuthService auth = AuthService.getInstance();

  /**
   * Creates new form SignInOne
   */
  public SignIn() {
	  FlatLightLaf.setup();
    this.setUndecorated(true);
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                btnSignIn = new javax.swing.JButton();
                txtEmail = new javax.swing.JTextField();
                txtPassword = new javax.swing.JPasswordField();
                btnClose = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                linkForgotPassword = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                windowBar1 = new com.group5.paul_esys.components.WindowBar();
                jLabel2 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));
                jPanel2.setPreferredSize(new java.awt.Dimension(1280, 720));

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));
                jPanel3.setBorder(new com.group5.paul_esys.ui.PanelRoundBorder());

                jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel4.setText("Email:");

                jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel5.setText("Password:");

                btnSignIn.setBackground(new java.awt.Color(255, 234, 234));
                btnSignIn.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                btnSignIn.setText("Sign in");
                btnSignIn.addActionListener(this::btnSignInActionPerformed);

                txtEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                txtEmail.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                txtPassword.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                txtPassword.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
                txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtPasswordKeyReleased(evt);
                        }
                });

                btnClose.setBackground(new java.awt.Color(255, 234, 234));
                btnClose.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                btnClose.setText("Close");
                btnClose.addActionListener(this::btnCloseActionPerformed);

                jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("Log in to VBSU");

                linkForgotPassword.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                linkForgotPassword.setForeground(new java.awt.Color(153, 153, 153));
                linkForgotPassword.setText("Forgot Password?");
                linkForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                linkForgotPasswordMouseClicked(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel6.setText("Welcome to VBSU Enrollment System");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(153, 153, 153));
                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel8.setText("It's simple and easy");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(linkForgotPassword)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtEmail)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(10, 10, 10))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 28, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linkForgotPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSignIn)
                                        .addComponent(btnClose))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("UNIVERSITY");

                windowBar1.setTitle("Welcome to Vince Batecan State University");

                jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("VINCE BATECAN STATE");

                jPanel1.setBackground(new java.awt.Color(102, 51, 0));
                jPanel1.setLayout(new java.awt.BorderLayout());

                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
                jPanel1.add(jLabel7, java.awt.BorderLayout.CENTER);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(34, 34, 34))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(windowBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(windowBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

  private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_txtPasswordKeyReleased
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      btnSignIn.doClick();
    }
  }//GEN-LAST:event_txtPasswordKeyReleased

  private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
    // GEN-FIRST:event_btnCloseActionPerformed
    this.dispose();
  } // GEN-LAST:event_btnCloseActionPerformed

  private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {
    // GEN-FIRST:event_btnSignInActionPerformed
    String email = txtEmail.getText();
    String password = new String(txtPassword.getPassword());

    if (email.isEmpty() || password.isEmpty()) {
      JOptionPane.showMessageDialog(
        this,
        "Please fill in all fields",
        "Error",
        JOptionPane.ERROR_MESSAGE
      );
      return;
    }

    Optional<UserInformation<?>> userInformationOptional = this.auth.login(
      new LoginData(email, password)
    );

    if (userInformationOptional.isPresent()) {
      UserInformation<?> userInformation = userInformationOptional.get();

      UserSession.getInstance().setUserInformation(userInformation);

      switch (userInformation.getRole()) {
        case STUDENT -> {
          StudentDashboard form = new StudentDashboard();
          form.setVisible(true);
        }
        case REGISTRAR -> {
          RegistrarDashboard form = new RegistrarDashboard();
          form.setVisible(true);
        }
        case FACULTY -> {
          // Yung faculty dashboard show dito
	  FacultyDashboard form = new FacultyDashboard();
	  form.setVisible(true);
        }
                                case ADMIN -> {
                                        AdminDashboard form = new AdminDashboard();
                                        form.setVisible(true);
                                }
      }

      logger.info("User is: " + userInformation.getUser().getClass().getName());
      logger.info("User logged in: " + userInformation.getEmail());
      this.dispose();
    } else {
      JOptionPane.showMessageDialog(
        this,
        "Invalid email or password",
        "Error",
        JOptionPane.ERROR_MESSAGE
      );
    }
  } // GEN-LAST:event_btnSignInActionPerformed

  private void linkForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {
    // GEN-FIRST:event_linkForgotPasswordMouseClicked
    ForgotPasswordForm form = new ForgotPasswordForm();
    form.setVisible(true);
  } // GEN-LAST:event_linkForgotPasswordMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new SignIn().setVisible(true));
  }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnClose;
        private javax.swing.JButton btnSignIn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JLabel linkForgotPassword;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JPasswordField txtPassword;
        private com.group5.paul_esys.components.WindowBar windowBar1;
        // End of variables declaration//GEN-END:variables
}
