/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group5.paul_esys;

import java.util.Optional;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import com.formdev.flatlaf.FlatLightLaf;
import com.group5.paul_esys.modules.users.models.user.LoginData;
import com.group5.paul_esys.modules.users.models.user.UserInformation;
import com.group5.paul_esys.modules.users.services.AuthService;

/**
 *
 * @author nytri
 */
public class SignIn extends javax.swing.JFrame {

	private static final java.util.logging.Logger logger = java.util.logging.Logger
			.getLogger(SignIn.class.getName());
	private final AuthService authService = new AuthService();

	/**
	 * Creates new form Login
	 */
	public SignIn() {
		this.setUndecorated(true);
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtEmail = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtPassword = new javax.swing.JPasswordField();
		btnSignIn = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		btnClose = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Sign in");
		setAlwaysOnTop(true);
		setBackground(new java.awt.Color(255, 255, 255));
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setLocation(new java.awt.Point(0, 0));
		setMinimumSize(new java.awt.Dimension(500, 250));
		setName("frameSignIn"); // NOI18N
		setResizable(false);
		setSize(new java.awt.Dimension(1280, 720));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setPreferredSize(new java.awt.Dimension(960, 480));
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(80, 17, 240));
		jLabel1.setText("Welcome back!");
		jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

		jLabel2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(102, 102, 102));
		jLabel2.setText("Sign in to access your enrollment portal");
		jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

		jLabel3.setText("Email Address");
		jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 139, -1, -1));
		jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 163, 263, -1));

		jLabel4.setText("Password");
		jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 221, -1, -1));
		jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 245, 263, -1));

		btnSignIn.setText("Sign in");
		btnSignIn.addActionListener(this::btnSignInActionPerformed);
		jPanel2.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 314, 126, 36));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 0, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 0, Short.MAX_VALUE));

		jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 0, -1, 401));

		btnClose.setText("Close");
		btnClose.addActionListener(this::btnCloseActionPerformed);
		jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 314, 131, 36));

		jPanel3.setBackground(new java.awt.Color(51, 153, 255));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 960, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 30, Short.MAX_VALUE));

		jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSignInActionPerformed
		if (this.txtEmail.getText().equals("")) {
			JOptionPane.showMessageDialog(rootPane, "Email address cannot be blank", "Error",
					JOptionPane.ERROR_MESSAGE);
		} else if (this.txtPassword.getPassword().length < 8) {
			JOptionPane.showMessageDialog(rootPane, "Password length cannot be less than 8 characters",
					"Error", JOptionPane.ERROR_MESSAGE);
		}

		Optional<UserInformation> userInfo = this.authService.login(new LoginData(
				this.txtEmail.getText(),
				String.valueOf(this.txtPassword.getPassword())));

		if (userInfo.isEmpty()) {
			JOptionPane.showMessageDialog(rootPane, "Email or password is incorrect!", "Error",
					JOptionPane.ERROR_MESSAGE);
		}

		userInfo.ifPresent(user -> {
			JOptionPane.showMessageDialog(rootPane, "Sign in successful!", "Success",
					JOptionPane.INFORMATION_MESSAGE);
		});
	}// GEN-LAST:event_btnSignInActionPerformed

	private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCloseActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnCloseActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			UIManager.setLookAndFeel(new FlatLightLaf());
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new SignIn().setVisible(true));
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnClose;
	private javax.swing.JButton btnSignIn;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JPasswordField txtPassword;
	// End of variables declaration//GEN-END:variables
}
