/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group5.paul_esys.screens.student;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTGitHubIJTheme;
import com.group5.paul_esys.modules.students.model.Student;
import com.group5.paul_esys.modules.users.services.UserSession;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Shan
 */
public class StudentDashboard extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger =
    java.util.logging.Logger.getLogger(StudentDashboard.class.getName());

  /**
   * Creates new form Dashboard
   */
  public StudentDashboard() {
    UIManager.put("TabbedPane.tabType", "underline");
    UIManager.put("TabbedPane.arc", 10);
    UIManager.put("TabbedPane.tabHeight", 36);
    UIManager.put("TabbedPane.tabInsets", new Insets(8, 16, 8, 16));

    UIManager.put("TabbedPane.selectedForeground", Color.BLACK);
    UIManager.put("TabbedPane.foreground", Color.GRAY);

    UIManager.put("TabbedPane.underlineColor", new Color(0, 120, 215));
    UIManager.put("TabbedPane.hoverColor", new Color(230, 230, 230));

    UIManager.put("TabbedPane.contentBorderInsets", new Insets(0, 0, 0, 0));
    UIManager.put("TabbedPane.showContentSeparator", false);
    FlatMTGitHubIJTheme.setup();

    Student student = (Student) UserSession.getInstance()
      .getUserInformation()
      .getUser();
    String fullName = String.format(
      "%s, %s %s",
      student.getLastName(),
      student.getFirstName(),
      (student.getMiddleName() != null) ? student.getMiddleName() : ""
    );

    this.setUndecorated(true);
    initComponents();
    this.setLocationRelativeTo(null);
    this.windowBar1.setTitle(fullName);
  }

  /**
   * This method is called from within the constructor to initialize the
   * form. WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    windowBar1 = new com.group5.paul_esys.components.WindowBar();
    tabbedPane = new javax.swing.JTabbedPane();
    panelDashboard = new javax.swing.JPanel();
    panelAcademicOverview = new javax.swing.JPanel();
    jLabel18 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jLabel19 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jTextField4 = new javax.swing.JTextField();
    jTextField5 = new javax.swing.JTextField();
    jLabel21 = new javax.swing.JLabel();
    jTextField6 = new javax.swing.JTextField();
    jLabel22 = new javax.swing.JLabel();
    jTextField7 = new javax.swing.JTextField();
    jLabel23 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jTextField8 = new javax.swing.JTextField();
    jLabel24 = new javax.swing.JLabel();
    jTextField9 = new javax.swing.JTextField();
    jLabel25 = new javax.swing.JLabel();
    jTextField10 = new javax.swing.JTextField();
    jLabel26 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel27 = new javax.swing.JLabel();
    jTextField11 = new javax.swing.JTextField();
    jTextField12 = new javax.swing.JTextField();
    jLabel28 = new javax.swing.JLabel();
    jTextField13 = new javax.swing.JTextField();
    jLabel29 = new javax.swing.JLabel();
    jTextField14 = new javax.swing.JTextField();
    jLabel30 = new javax.swing.JLabel();
    jTextField15 = new javax.swing.JTextField();
    jLabel31 = new javax.swing.JLabel();
    panelEnrollmentProgress = new javax.swing.JPanel();
    btnOpenRegistration = new javax.swing.JButton();
    pBarRegistration = new javax.swing.JProgressBar();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    panelCourseRegistration = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    txtSearch = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblSubjectCatalog = new javax.swing.JTable();
    jLabel14 = new javax.swing.JLabel();
    btnSearchSubject = new javax.swing.JButton();
    jPanel8 = new javax.swing.JPanel();
    jLabel15 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jTextField3 = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    btnSubmitSchedule = new javax.swing.JButton();
    panelMySchedule = new javax.swing.JPanel();
    jPanel9 = new javax.swing.JPanel();
    jPanel10 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTable2 = new javax.swing.JTable();
    jLabel12 = new javax.swing.JLabel();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);
    getContentPane().setLayout(
      new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS)
    );

    windowBar1.setTitle("Student Dashboard");
    getContentPane().add(windowBar1);

    tabbedPane.setBorder(
      javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(225, 225, 225)
      )
    );
    tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
    tabbedPane.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

    panelDashboard.setBackground(new java.awt.Color(255, 255, 255));

    panelAcademicOverview.setBackground(new java.awt.Color(255, 255, 255));
    panelAcademicOverview.setBorder(
      new com.group5.paul_esys.ui.RoundShadowBorder()
    );

    jLabel18.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel18.setText("Student ID");

    jTextField1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField1.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jTextField2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField2.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel19.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel19.setText("Email Address");

    jLabel20.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel20.setText("First Name");

    jTextField4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField4.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jTextField5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField5.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel21.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel21.setText("Middle Name");

    jTextField6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField6.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel22.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel22.setText("Last Name");

    jTextField7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField7.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel23.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel23.setText("Birth Date");

    jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 102));
    jLabel1.setText("Student Information");

    jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(153, 153, 153));
    jLabel4.setText("Read your information on the fly");

    jTextField8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField8.setText("REGULAR");
    jTextField8.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel24.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel24.setText("Student Status");

    jTextField9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField9.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel25.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel25.setText("Course / Program");

    jTextField10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField10.setText("REGULAR");
    jTextField10.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel26.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel26.setText("Year Level");

    jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(153, 153, 153));
    jLabel8.setText("See Enrollment Activity");

    jLabel9.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(0, 0, 102));
    jLabel9.setText("Academic Overview");

    jLabel27.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel27.setText("Total Subjects");

    jTextField11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField11.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jTextField12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField12.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel28.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel28.setText("Total Units");

    jTextField13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField13.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel29.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel29.setText("Enrollment Status");

    jTextField14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField14.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel30.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel30.setText("Current Section");

    jTextField15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jTextField15.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

    jLabel31.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel31.setText("Enrollment Status");

    javax.swing.GroupLayout panelAcademicOverviewLayout =
      new javax.swing.GroupLayout(panelAcademicOverview);
    panelAcademicOverview.setLayout(panelAcademicOverviewLayout);
    panelAcademicOverviewLayout.setHorizontalGroup(
      panelAcademicOverviewLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          panelAcademicOverviewLayout
            .createSequentialGroup()
            .addContainerGap(27, Short.MAX_VALUE)
            .addGroup(
              panelAcademicOverviewLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  panelAcademicOverviewLayout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.LEADING,
                      false
                    )
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addGroup(
                      panelAcademicOverviewLayout
                        .createSequentialGroup()
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addComponent(jLabel18)
                            .addComponent(
                              jTextField1,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              300,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addPreferredGap(
                          javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                        )
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING,
                              false
                            )
                            .addComponent(
                              jTextField2,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              300,
                              Short.MAX_VALUE
                            )
                            .addComponent(
                              jLabel19,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE
                            )
                        )
                    )
                    .addComponent(
                      jLabel4,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addGroup(
                      panelAcademicOverviewLayout
                        .createSequentialGroup()
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addGroup(
                              panelAcademicOverviewLayout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                  false
                                )
                                .addComponent(
                                  jTextField7,
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  panelAcademicOverviewLayout
                                    .createSequentialGroup()
                                    .addGroup(
                                      panelAcademicOverviewLayout
                                        .createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING,
                                          false
                                        )
                                        .addComponent(
                                          jTextField4,
                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                          205,
                                          javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addComponent(
                                          jLabel20,
                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                          205,
                                          javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                    )
                                    .addPreferredGap(
                                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                    )
                                    .addGroup(
                                      panelAcademicOverviewLayout
                                        .createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.LEADING
                                        )
                                        .addComponent(jLabel21)
                                        .addComponent(
                                          jTextField5,
                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                          197,
                                          javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                    )
                                )
                                .addComponent(
                                  jLabel25,
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  205,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                  jTextField9,
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                            )
                            .addComponent(
                              jLabel23,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              205,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addPreferredGap(
                          javax.swing.LayoutStyle.ComponentPlacement.RELATED
                        )
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING,
                              false
                            )
                            .addComponent(jLabel22)
                            .addComponent(jTextField6)
                            .addComponent(jTextField8)
                            .addComponent(
                              jLabel24,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE
                            )
                            .addComponent(jTextField10)
                            .addComponent(
                              jLabel26,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              198,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                    .addComponent(
                      jLabel9,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
                .addGroup(
                  panelAcademicOverviewLayout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.TRAILING,
                      false
                    )
                    .addGroup(
                      javax.swing.GroupLayout.Alignment.LEADING,
                      panelAcademicOverviewLayout
                        .createSequentialGroup()
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING,
                              false
                            )
                            .addComponent(
                              jLabel30,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              296,
                              Short.MAX_VALUE
                            )
                            .addComponent(jTextField14)
                        )
                        .addPreferredGap(
                          javax.swing.LayoutStyle.ComponentPlacement.RELATED
                        )
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addComponent(jTextField15)
                            .addComponent(
                              jLabel31,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE
                            )
                        )
                        .addGap(21, 21, 21)
                    )
                    .addGroup(
                      javax.swing.GroupLayout.Alignment.LEADING,
                      panelAcademicOverviewLayout
                        .createSequentialGroup()
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addComponent(
                              jTextField11,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              205,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addComponent(
                              jLabel27,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              205,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addPreferredGap(
                          javax.swing.LayoutStyle.ComponentPlacement.RELATED
                        )
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addComponent(
                              jTextField12,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              205,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addComponent(
                              jLabel28,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              205,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addPreferredGap(
                          javax.swing.LayoutStyle.ComponentPlacement.RELATED
                        )
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addComponent(
                              jLabel29,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              205,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addComponent(
                              jTextField13,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              185,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                )
            )
            .addGap(9, 9, 9)
        )
    );
    panelAcademicOverviewLayout.setVerticalGroup(
      panelAcademicOverviewLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          panelAcademicOverviewLayout
            .createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(
              panelAcademicOverviewLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addComponent(jLabel24)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jTextField8,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(jLabel4)
                    .addGap(36, 36, 36)
                    .addGroup(
                      panelAcademicOverviewLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(
                          jLabel19,
                          javax.swing.GroupLayout.Alignment.TRAILING
                        )
                        .addComponent(
                          jLabel18,
                          javax.swing.GroupLayout.Alignment.TRAILING
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addGroup(
                      panelAcademicOverviewLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING
                        )
                        .addComponent(
                          jTextField2,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jTextField1,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addGroup(
                      panelAcademicOverviewLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel20)
                        .addGroup(
                          panelAcademicOverviewLayout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE
                            )
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addGroup(
                      panelAcademicOverviewLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(
                          jTextField5,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jTextField6,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jTextField4,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(jLabel23)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jTextField7,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              panelAcademicOverviewLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addComponent(jLabel25)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jTextField9,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addComponent(jLabel26)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jTextField10,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addGap(18, 18, 18)
            .addGroup(
              panelAcademicOverviewLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addComponent(jLabel27)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jTextField11,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addComponent(jLabel28)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jTextField12,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addComponent(jLabel29)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jTextField13,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addGroup(
              panelAcademicOverviewLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addGroup(
                      panelAcademicOverviewLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(jLabel30)
                        .addComponent(jLabel31)
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jTextField14,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  panelAcademicOverviewLayout
                    .createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(
                      jTextField15,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addContainerGap(64, Short.MAX_VALUE)
        )
    );

    panelEnrollmentProgress.setBorder(
      new com.group5.paul_esys.ui.RoundShadowBorder()
    );

    btnOpenRegistration.setText("Open Registration");
    btnOpenRegistration.addActionListener(
      this::btnOpenRegistrationActionPerformed
    );

    pBarRegistration.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );

    jLabel5.setText("Registration");

    jLabel6.setText("Approval");

    jLabel7.setText("Enrolled");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 102));
    jLabel2.setText("Enrollment Progress");

    javax.swing.GroupLayout panelEnrollmentProgressLayout =
      new javax.swing.GroupLayout(panelEnrollmentProgress);
    panelEnrollmentProgress.setLayout(panelEnrollmentProgressLayout);
    panelEnrollmentProgressLayout.setHorizontalGroup(
      panelEnrollmentProgressLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          panelEnrollmentProgressLayout
            .createSequentialGroup()
            .addGroup(
              panelEnrollmentProgressLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  panelEnrollmentProgressLayout
                    .createSequentialGroup()
                    .addContainerGap(
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(btnOpenRegistration)
                )
                .addGroup(
                  panelEnrollmentProgressLayout
                    .createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(
                      panelEnrollmentProgressLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(
                          pBarRegistration,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          Short.MAX_VALUE
                        )
                        .addGroup(
                          panelEnrollmentProgressLayout
                            .createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(270, 270, 270)
                            .addComponent(jLabel6)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                              90,
                              Short.MAX_VALUE
                            )
                            .addComponent(jLabel7)
                        )
                    )
                )
            )
            .addContainerGap()
        )
        .addGroup(
          panelEnrollmentProgressLayout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    panelEnrollmentProgressLayout.setVerticalGroup(
      panelEnrollmentProgressLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          panelEnrollmentProgressLayout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              jLabel2,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addGap(5, 5, 5)
            .addGroup(
              panelEnrollmentProgressLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7)
            )
            .addGap(4, 4, 4)
            .addComponent(
              pBarRegistration,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              15,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(7, 7, 7)
            .addComponent(btnOpenRegistration)
            .addContainerGap()
        )
    );

    javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(
      panelDashboard
    );
    panelDashboard.setLayout(panelDashboardLayout);
    panelDashboardLayout.setHorizontalGroup(
      panelDashboardLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          panelDashboardLayout
            .createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(
              panelAcademicOverview,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              panelEnrollmentProgress,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(270, Short.MAX_VALUE)
        )
    );
    panelDashboardLayout.setVerticalGroup(
      panelDashboardLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          panelDashboardLayout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              panelDashboardLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  panelDashboardLayout
                    .createSequentialGroup()
                    .addComponent(
                      panelEnrollmentProgress,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(0, 0, Short.MAX_VALUE)
                )
                .addComponent(
                  panelAcademicOverview,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addContainerGap()
        )
    );

    tabbedPane.addTab("Dashboard", panelDashboard);

    panelCourseRegistration.setBackground(new java.awt.Color(255, 255, 255));
    panelCourseRegistration.setBorder(
      javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(225, 225, 225)
      )
    );

    jLabel13.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    jLabel13.setText("Search Subjects");

    txtSearch.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    txtSearch.setToolTipText("Search for Subjects");
    txtSearch.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
    txtSearch.addActionListener(this::txtSearchActionPerformed);

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setBorder(new com.group5.paul_esys.ui.RoundShadowBorder());
    jPanel2.setForeground(new java.awt.Color(0, 0, 0));

    tblSubjectCatalog.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    tblSubjectCatalog.setModel(
      new javax.swing.table.DefaultTableModel(
        new Object[][] {
          { null, null, null, null },
          { null, null, null, null },
          { null, null, null, null },
          { null, null, null, null },
        },
        new String[] { "Subject Name", "Code", "Units", "Description" }
      ) {
        Class[] types = new Class[] {
          java.lang.String.class,
          java.lang.String.class,
          java.lang.Integer.class,
          java.lang.String.class,
        };

        public Class getColumnClass(int columnIndex) {
          return types[columnIndex];
        }
      }
    );
    jScrollPane1.setViewportView(tblSubjectCatalog);

    jLabel14.setText("Subject Catalog");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
      jPanel2
    );
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel2Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jScrollPane1,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  1127,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jLabel14,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addContainerGap()
        )
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addGap(13, 13, 13)
            .addComponent(jLabel14)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              568,
              Short.MAX_VALUE
            )
            .addContainerGap()
        )
    );

    btnSearchSubject.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    btnSearchSubject.setText("Search");
    btnSearchSubject.addActionListener(this::btnSearchSubjectActionPerformed);

    jPanel8.setBackground(new java.awt.Color(255, 255, 255));
    jPanel8.setBorder(new com.group5.paul_esys.ui.RoundShadowBorder());

    jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel15.setText("Selected");

    jTextField3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

    jLabel16.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel16.setText("Selected");

    jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel17.setText("0 / n units");

    btnSubmitSchedule.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    btnSubmitSchedule.setText("Submit Schedule");
    btnSubmitSchedule.addActionListener(this::btnSubmitScheduleActionPerformed);

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
      jPanel8
    );
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel8Layout
            .createSequentialGroup()
            .addGroup(
              jPanel8Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jSeparator1,
                  javax.swing.GroupLayout.Alignment.TRAILING
                )
                .addComponent(
                  jSeparator2,
                  javax.swing.GroupLayout.Alignment.TRAILING
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel8Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                      jPanel8Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(
                          jLabel17,
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          Short.MAX_VALUE
                        )
                        .addComponent(
                          jTextField3,
                          javax.swing.GroupLayout.Alignment.TRAILING
                        )
                    )
                )
                .addGroup(
                  jPanel8Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel8Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel8Layout
                            .createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addGroup(
                              jPanel8Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(jLabel16)
                                .addComponent(jLabel15)
                            )
                        )
                        .addGroup(
                          jPanel8Layout
                            .createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(
                              btnSubmitSchedule,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              219,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                    .addGap(0, 78, Short.MAX_VALUE)
                )
            )
            .addContainerGap()
        )
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel8Layout
            .createSequentialGroup()
            .addGap(11, 11, 11)
            .addComponent(jLabel15)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jTextField3,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(
              jSeparator1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              10,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jLabel16)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel17)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jSeparator2,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              10,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              btnSubmitSchedule,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              45,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    javax.swing.GroupLayout panelCourseRegistrationLayout =
      new javax.swing.GroupLayout(panelCourseRegistration);
    panelCourseRegistration.setLayout(panelCourseRegistrationLayout);
    panelCourseRegistrationLayout.setHorizontalGroup(
      panelCourseRegistrationLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          panelCourseRegistrationLayout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              panelCourseRegistrationLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jPanel2,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addGroup(
                  panelCourseRegistrationLayout
                    .createSequentialGroup()
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)
                )
                .addGroup(
                  panelCourseRegistrationLayout
                    .createSequentialGroup()
                    .addComponent(txtSearch)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      btnSearchSubject,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      161,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jPanel8,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap()
        )
    );
    panelCourseRegistrationLayout.setVerticalGroup(
      panelCourseRegistrationLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          panelCourseRegistrationLayout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel13)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              panelCourseRegistrationLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  panelCourseRegistrationLayout
                    .createSequentialGroup()
                    .addGroup(
                      panelCourseRegistrationLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(
                          txtSearch,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(btnSearchSubject)
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jPanel2,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
                .addComponent(
                  jPanel8,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addContainerGap()
        )
    );

    tabbedPane.addTab("Course Registration", panelCourseRegistration);

    panelMySchedule.setBackground(new java.awt.Color(255, 255, 255));
    panelMySchedule.setBorder(
      javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(225, 225, 225)
      )
    );

    jPanel9.setBackground(new java.awt.Color(255, 255, 255));
    jPanel9.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );

    jPanel10.setBackground(new java.awt.Color(247, 231, 244));
    jPanel10.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(
      java.awt.FlowLayout.LEFT
    );
    flowLayout1.setAlignOnBaseline(true);
    jPanel10.setLayout(flowLayout1);

    jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
    jLabel3.setText("Status: Pending Approval");
    jPanel10.add(jLabel3);

    jTable2.setModel(
      new javax.swing.table.DefaultTableModel(
        new Object[][] {
          { null, null, null, null, null, null },
          { null, null, null, null, null, null },
          { null, null, null, null, null, null },
          { null, null, null, null, null, null },
        },
        new String[] {
          "Code",
          "Course Name",
          "Instructor",
          "Schedule",
          "Room",
          "Credits",
        }
      )
    );
    jScrollPane2.setViewportView(jTable2);

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
      jPanel9
    );
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel9Layout
            .createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(
              jPanel9Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jScrollPane2,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  1525,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jPanel10,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addContainerGap()
        )
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel9Layout
            .createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(
              jPanel10,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jScrollPane2,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              601,
              Short.MAX_VALUE
            )
            .addContainerGap()
        )
    );

    jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
    jLabel12.setText("Class Schedule");

    jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jButton4.setText("Print Schedule");

    jButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
    jButton5.setText("Export PDF");

    javax.swing.GroupLayout panelMyScheduleLayout = new javax.swing.GroupLayout(
      panelMySchedule
    );
    panelMySchedule.setLayout(panelMyScheduleLayout);
    panelMyScheduleLayout.setHorizontalGroup(
      panelMyScheduleLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          panelMyScheduleLayout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              panelMyScheduleLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jPanel9,
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  panelMyScheduleLayout
                    .createSequentialGroup()
                    .addComponent(jLabel12)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(jButton5)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(jButton4)
                )
            )
            .addContainerGap()
        )
    );
    panelMyScheduleLayout.setVerticalGroup(
      panelMyScheduleLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          panelMyScheduleLayout
            .createSequentialGroup()
            .addGroup(
              panelMyScheduleLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  panelMyScheduleLayout
                    .createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(
                      panelMyScheduleLayout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(jButton4)
                        .addComponent(jButton5)
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                    )
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  panelMyScheduleLayout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12)
                    .addGap(3, 3, 3)
                )
            )
            .addComponent(
              jPanel9,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addContainerGap()
        )
    );

    tabbedPane.addTab("My Schedule", panelMySchedule);

    getContentPane().add(tabbedPane);

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void btnOpenRegistrationActionPerformed(
    java.awt.event.ActionEvent evt
  ) {
    //GEN-FIRST:event_btnOpenRegistrationActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_btnOpenRegistrationActionPerformed

  private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_txtSearchActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_txtSearchActionPerformed

  private void btnSearchSubjectActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_btnSearchSubjectActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_btnSearchSubjectActionPerformed

  private void btnSubmitScheduleActionPerformed(
    java.awt.event.ActionEvent evt
  ) {
    //GEN-FIRST:event_btnSubmitScheduleActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_btnSubmitScheduleActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() ->
      new StudentDashboard().setVisible(true)
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnOpenRegistration;
  private javax.swing.JButton btnSearchSubject;
  private javax.swing.JButton btnSubmitSchedule;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel25;
  private javax.swing.JLabel jLabel26;
  private javax.swing.JLabel jLabel27;
  private javax.swing.JLabel jLabel28;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel30;
  private javax.swing.JLabel jLabel31;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel10;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JTable jTable2;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField10;
  private javax.swing.JTextField jTextField11;
  private javax.swing.JTextField jTextField12;
  private javax.swing.JTextField jTextField13;
  private javax.swing.JTextField jTextField14;
  private javax.swing.JTextField jTextField15;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private javax.swing.JTextField jTextField8;
  private javax.swing.JTextField jTextField9;
  private javax.swing.JProgressBar pBarRegistration;
  private javax.swing.JPanel panelAcademicOverview;
  private javax.swing.JPanel panelCourseRegistration;
  private javax.swing.JPanel panelDashboard;
  private javax.swing.JPanel panelEnrollmentProgress;
  private javax.swing.JPanel panelMySchedule;
  private javax.swing.JTabbedPane tabbedPane;
  private javax.swing.JTable tblSubjectCatalog;
  private javax.swing.JTextField txtSearch;
  private com.group5.paul_esys.components.WindowBar windowBar1;
  // End of variables declaration//GEN-END:variables
}
