/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group5.paul_esys.components;

import java.awt.Frame;
import java.awt.Window;
import javax.swing.SwingUtilities;

/**
 *
 * @author nytri
 */
public class WindowBar extends javax.swing.JPanel {

	private String title = "Title";

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		String oldTitle = this.title;
		this.title = title;

		// Important: Fire the event so the GUI builder knows the property changed
		firePropertyChange("title", oldTitle, title);
		jLabel3.setText(title);

		// Redraw the component in the design view
		repaint();
	}

	/**
	 * Creates new form WindowBar
	 */
	public WindowBar() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                btnMinimize = new javax.swing.JLabel();
                btnClose = new javax.swing.JLabel();

                setBackground(new java.awt.Color(119, 0, 0));
                setPreferredSize(new java.awt.Dimension(430, 36));
                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

                jPanel2.setBackground(new java.awt.Color(119, 0, 0));
                java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 8);
                flowLayout1.setAlignOnBaseline(true);
                jPanel2.setLayout(flowLayout1);

                jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Title");
                jPanel2.add(jLabel3);

                add(jPanel2);

                jPanel3.setBackground(new java.awt.Color(119, 0, 0));
                jPanel3.setPreferredSize(new java.awt.Dimension(63, 36));
                java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 6);
                flowLayout2.setAlignOnBaseline(true);
                jPanel3.setLayout(flowLayout2);

                btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
                btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnMinimizeMouseClicked(evt);
                        }
                });
                jPanel3.add(btnMinimize);

                btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
                btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnCloseMouseClicked(evt);
                        }
                });
                jPanel3.add(btnClose);

                add(jPanel3);
        }// </editor-fold>//GEN-END:initComponents

        private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
		Window window = SwingUtilities.getWindowAncestor(this);
		window.dispose();
        }//GEN-LAST:event_btnCloseMouseClicked

        private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
		Window window = SwingUtilities.getWindowAncestor(this);
		Frame frame = (Frame) window;
		frame.setExtendedState(Frame.ICONIFIED);
        }//GEN-LAST:event_btnMinimizeMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel btnClose;
        private javax.swing.JLabel btnMinimize;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        // End of variables declaration//GEN-END:variables
}
