package com.group5.paul_esys.screens.registrar.forms;

import com.group5.paul_esys.modules.courses.model.Course;
import com.group5.paul_esys.modules.courses.services.CourseService;
import com.group5.paul_esys.modules.departments.model.Department;
import com.group5.paul_esys.modules.departments.services.DepartmentService;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author janea
 */
public class CourseForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseForm.class.getName());
    private final CourseService courseService = CourseService.getInstance();
    private final DepartmentService departmentService = DepartmentService.getInstance();
    private final Map<String, Long> departmentIdByName = new LinkedHashMap<>();
    private final Runnable onSavedCallback;
    private final Course editingCourse;

    /**
     * Creates new form CourseForm
     */
    public CourseForm() {
        this(null, null);
    }

    public CourseForm(Course editingCourse, Runnable onSavedCallback) {
        this.editingCourse = editingCourse;
        this.onSavedCallback = onSavedCallback;
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        initializeForm();
    }

    private void initializeForm() {
        loadDepartments();

        if (editingCourse != null) {
            jLabel1.setText("Update Course");
            jLabel5.setText("Update existing course");
            btnSave.setText("Update");

            txtCourse.setText(editingCourse.getCourseName());
            txtAreaDescription.setText(
                editingCourse.getDescription() == null ? "" : editingCourse.getDescription()
            );

            departmentService
                .getDepartmentById(editingCourse.getDepartmentId())
                .ifPresent(department -> cbxDep.setSelectedItem(department.getDepartmentName()));
        }
    }

    private void loadDepartments() {
        cbxDep.removeAllItems();
        departmentIdByName.clear();

        for (Department department : departmentService.getAllDepartments()) {
            cbxDep.addItem(department.getDepartmentName());
            departmentIdByName.put(department.getDepartmentName(), department.getId());
        }
    }

    private boolean isValidForm() {
        if (txtCourse.getText() == null || txtCourse.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Course name is required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        Object selectedDepartment = cbxDep.getSelectedItem();
        if (selectedDepartment == null || !departmentIdByName.containsKey(selectedDepartment.toString())) {
            JOptionPane.showMessageDialog(
                this,
                "Department is required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        return true;
    }

    private void saveCourse() {
        if (!isValidForm()) {
            return;
        }

        String selectedDepartment = cbxDep.getSelectedItem().toString();
        Long departmentId = departmentIdByName.get(selectedDepartment);

        Course course = editingCourse == null ? new Course() : editingCourse;
        course
            .setCourseName(txtCourse.getText().trim())
            .setDescription(txtAreaDescription.getText().trim())
            .setDepartmentId(departmentId);

        boolean success =
            editingCourse == null
                ? courseService.createCourse(course)
                : courseService.updateCourse(course);

        if (!success) {
            JOptionPane.showMessageDialog(
                this,
                "Failed to save course. Please try again.",
                "Save Failed",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        JOptionPane.showMessageDialog(
            this,
            editingCourse == null
                ? "Course created successfully."
                : "Course updated successfully.",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );

        if (onSavedCallback != null) {
            onSavedCallback.run();
        }

        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                windowBar2 = new com.group5.paul_esys.components.WindowBar();
                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                txtCourse = new javax.swing.JTextField();
                cbxDep = new javax.swing.JComboBox<>();
                jLabel1 = new javax.swing.JLabel();
                btnCancel = new javax.swing.JButton();
                btnSave = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtAreaDescription = new javax.swing.JTextArea();
                jLabel5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

                windowBar2.setTitle("Course Form");
                getContentPane().add(windowBar2);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setAlignmentX(0.1F);
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel2.setText("Description");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

                jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel3.setText("Department");
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

                jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel4.setText("Course");
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

                txtCourse.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                txtCourse.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());
                jPanel1.add(txtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 250, -1));

                cbxDep.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jPanel1.add(cbxDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 250, 36));

                jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Course Form");
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 30, 240, -1));

                btnCancel.setBackground(new java.awt.Color(255, 234, 234));
                btnCancel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                btnCancel.setText("Cancel");
                btnCancel.addActionListener(this::btnCancelActionPerformed);
                jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 100, -1));

                btnSave.setBackground(new java.awt.Color(255, 234, 234));
                btnSave.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                btnSave.setText("Save");
                btnSave.addActionListener(this::btnSaveActionPerformed);
                jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 100, -1));

                txtAreaDescription.setColumns(20);
                txtAreaDescription.setRows(5);
                txtAreaDescription.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtAreaDescriptionKeyReleased(evt);
                        }
                });
                jScrollPane1.setViewportView(txtAreaDescription);

                jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 250, 140));

                jLabel5.setForeground(new java.awt.Color(102, 102, 102));
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("Add/Update a Course");
                jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 250, -1));

                getContentPane().add(jPanel1);

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveCourse();
    }//GEN-LAST:event_btnSaveActionPerformed

        private void txtAreaDescriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaDescriptionKeyReleased
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                saveCourse();
            }
        }//GEN-LAST:event_txtAreaDescriptionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseForm().setVisible(true));
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSave;
        private javax.swing.JComboBox<String> cbxDep;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea txtAreaDescription;
        private javax.swing.JTextField txtCourse;
        private com.group5.paul_esys.components.WindowBar windowBar2;
        // End of variables declaration//GEN-END:variables
}
