package com.group5.paul_esys.screens.registrar.forms;

import java.awt.Dialog;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

import com.group5.paul_esys.modules.registrar.model.ScheduleGenerationPlanRow;
import com.group5.paul_esys.modules.registrar.model.ScheduleGenerationRequest;
import com.group5.paul_esys.modules.registrar.model.ScheduleGenerationResult;
import com.group5.paul_esys.modules.registrar.model.ScheduleGenerationSectionOption;
import com.group5.paul_esys.modules.registrar.services.RegistrarScheduleManagementService;

public class ScheduleGenerationDialog extends JDialog {

  private static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("HH:mm");

  private final RegistrarScheduleManagementService scheduleManagementService;
  private final Runnable onGenerationCommitted;

  private final DefaultTableModel tableModel = new DefaultTableModel(
      new Object[][] {},
      new String[] { "Subject Code", "Subject Name", "Pattern", "Block", "Estimated (min)", "Day", "Time", "Room",
          "Status", "Details" }) {
    @Override
    public boolean isCellEditable(int row, int column) {
      return false;
    }
  };

  private final List<ScheduleGenerationSectionOption> sectionOptions = new ArrayList<>();

  private ScheduleGenerationResult lastPreviewResult;

  public ScheduleGenerationDialog(
      Frame parent,
      RegistrarScheduleManagementService scheduleManagementService,
      Runnable onGenerationCommitted) {
    super(parent, true);
    this.scheduleManagementService = scheduleManagementService;
    this.onGenerationCommitted = onGenerationCommitted;

    setUndecorated(true);
    setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    initComponents();
    initializeData();
    pack();
    setLocationRelativeTo(parent);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    windowBar1 = new com.group5.paul_esys.components.WindowBar();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    cbxSectionPeriod = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    txtMinStartTime = new javax.swing.JFormattedTextField();
    jLabel5 = new javax.swing.JLabel();
    txtMaxEndTime = new javax.swing.JFormattedTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblPreview = new javax.swing.JTable();
    lblSummary = new javax.swing.JLabel();
    btnPreview = new javax.swing.JButton();
    btnGenerate = new javax.swing.JButton();
    btnClose = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Auto Schedule Generator");

    windowBar1.setPreferredSize(new java.awt.Dimension(0, 38));
    windowBar1.setTitle("Auto Schedule Generator");

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setPreferredSize(new java.awt.Dimension(950, 470));

    jLabel1.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Generate Section Schedules");

    jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(120, 120, 120));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Preview and generate conflict-aware schedules within your selected time window.");

    jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
    jLabel3.setText("Section + Enrollment Period");

    cbxSectionPeriod.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

    jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
    jLabel4.setText("Minimum Start Time (HH:mm)");

    txtMinStartTime.setText("07:30");
    txtMinStartTime.setToolTipText("Use HH:mm format (example: 07:30)");
    txtMinStartTime.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

    jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
    jLabel5.setText("Maximum End Time (HH:mm)");

    txtMaxEndTime.setText("18:00");
    txtMaxEndTime.setToolTipText("Use HH:mm format (example: 18:00)");
    txtMaxEndTime.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

    tblPreview.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {

        },
        new String[] {
            "Subject Code", "Subject Name", "Pattern", "Block", "Estimated (min)", "Day", "Time", "Room", "Status",
            "Details"
        }) {
      boolean[] canEdit = new boolean[] {
          false, false, false, false, false, false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit[columnIndex];
      }
    });
    tblPreview.setRowHeight(24);
    tblPreview.setFillsViewportHeight(true);
    jScrollPane1.setViewportView(tblPreview);

    lblSummary.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
    lblSummary.setForeground(new java.awt.Color(75, 75, 75));
    lblSummary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lblSummary.setText("Run preview to view generated schedule rows.");

    btnPreview.setBackground(new java.awt.Color(119, 0, 0));
    btnPreview.setForeground(new java.awt.Color(255, 255, 255));
    btnPreview.setText("Preview");

    btnGenerate.setBackground(new java.awt.Color(119, 0, 0));
    btnGenerate.setForeground(new java.awt.Color(255, 255, 255));
    btnGenerate.setText("Generate");

    btnClose.setBackground(new java.awt.Color(119, 0, 0));
    btnClose.setForeground(new java.awt.Color(255, 255, 255));
    btnClose.setText("Close");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(cbxSectionPeriod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(txtMinStartTime)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(txtMaxEndTime)
                    .addComponent(jScrollPane1)
                    .addComponent(lblSummary, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSectionPeriod, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMinStartTime, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaxEndTime, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSummary)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreview)
                    .addComponent(btnGenerate)
                    .addComponent(btnClose))
                .addContainerGap(16, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 751,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 751,
                javax.swing.GroupLayout.PREFERRED_SIZE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(windowBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639,
                    javax.swing.GroupLayout.PREFERRED_SIZE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPreviewActionPerformed
    previewGeneration();
  }// GEN-LAST:event_btnPreviewActionPerformed

  private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGenerateActionPerformed
    executeGeneration();
  }// GEN-LAST:event_btnGenerateActionPerformed

  private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCloseActionPerformed
    dispose();
  }// GEN-LAST:event_btnCloseActionPerformed

  private void initializeData() {
    sectionOptions.clear();
    sectionOptions.addAll(scheduleManagementService.getSectionGenerationOptions());

    cbxSectionPeriod.removeAllItems();
    if (sectionOptions.isEmpty()) {
      cbxSectionPeriod.addItem("No section options available");
      cbxSectionPeriod.setEnabled(false);
      lblSummary.setText("No offerings found. Create offerings first before generating schedules.");
      return;
    }

    cbxSectionPeriod.setEnabled(true);
    for (ScheduleGenerationSectionOption option : sectionOptions) {
      String capacity = option.sectionCapacity() == null || option.sectionCapacity() <= 0
          ? "Open"
          : String.valueOf(option.sectionCapacity());
      cbxSectionPeriod.addItem(
          option.sectionCode() + " | " + option.enrollmentPeriodLabel() + " | Cap " + capacity);
    }
  }

  private void previewGeneration() {
    ScheduleGenerationRequest request = buildRequest();
    if (request == null) {
      return;
    }

    lblSummary.setText("Preparing preview...");
    runGenerationTask(request, false);
  }

  private void executeGeneration() {
    ScheduleGenerationRequest request = buildRequest();
    if (request == null) {
      return;
    }

    if (lastPreviewResult == null) {
      int choice = JOptionPane.showConfirmDialog(
          this,
          "No preview found yet. Generate now anyway?",
          "Generate Without Preview",
          JOptionPane.YES_NO_OPTION,
          JOptionPane.WARNING_MESSAGE);

      if (choice != JOptionPane.YES_OPTION) {
        return;
      }
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Generate schedules for the selected section now?",
        "Confirm Generation",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);

    if (confirm != JOptionPane.YES_OPTION) {
      return;
    }

    lblSummary.setText("Generating schedules...");
    runGenerationTask(request, true);
  }

  private void runGenerationTask(ScheduleGenerationRequest request, boolean persist) {
    new SwingWorker<ScheduleGenerationResult, Void>() {
      @Override
      protected ScheduleGenerationResult doInBackground() {
        return persist
            ? scheduleManagementService.generateSectionSchedules(request)
            : scheduleManagementService.previewSectionScheduleGeneration(request);
      }

      @Override
      protected void done() {
        try {
          ScheduleGenerationResult result = get();
          if (!persist) {
            lastPreviewResult = result;
          }

          populatePreviewRows(result.rows());
          lblSummary.setText(result.message());

          if (!result.successful()) {
            JOptionPane.showMessageDialog(
                ScheduleGenerationDialog.this,
                result.message(),
                "Schedule Generator",
                JOptionPane.ERROR_MESSAGE);
            return;
          }

          if (persist && onGenerationCommitted != null) {
            onGenerationCommitted.run();
          }
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(
              ScheduleGenerationDialog.this,
              "Error processing generation: " + ex.getMessage(),
              "Schedule Generator",
              JOptionPane.ERROR_MESSAGE);
        }
      }
    }.execute();
  }

  private ScheduleGenerationRequest buildRequest() {
    int selectedIndex = cbxSectionPeriod.getSelectedIndex();
    if (selectedIndex < 0 || selectedIndex >= sectionOptions.size()) {
      JOptionPane.showMessageDialog(
          this,
          "Please select a section and enrollment period.",
          "Schedule Generator",
          JOptionPane.WARNING_MESSAGE);
      return null;
    }

    LocalTime minStart = parseTime(txtMinStartTime.getText());
    LocalTime maxEnd = parseTime(txtMaxEndTime.getText());

    if (minStart == null || maxEnd == null) {
      JOptionPane.showMessageDialog(
          this,
          "Please use HH:mm format for both time fields.",
          "Schedule Generator",
          JOptionPane.WARNING_MESSAGE);
      return null;
    }

    if (!minStart.isBefore(maxEnd)) {
      JOptionPane.showMessageDialog(
          this,
          "Minimum start time must be earlier than maximum end time.",
          "Schedule Generator",
          JOptionPane.WARNING_MESSAGE);
      return null;
    }

    ScheduleGenerationSectionOption selected = sectionOptions.get(selectedIndex);
    return new ScheduleGenerationRequest(
        selected.sectionId(),
        selected.enrollmentPeriodId(),
        minStart,
        maxEnd,
        30);
  }

  private void populatePreviewRows(List<ScheduleGenerationPlanRow> rows) {
    tableModel.setRowCount(0);

    for (ScheduleGenerationPlanRow row : rows) {
      String timeRange = row.startTime() == null || row.endTime() == null
          ? "N/A"
          : row.startTime().format(TIME_FORMATTER) + " - " + row.endTime().format(TIME_FORMATTER);

      tableModel.addRow(new Object[] {
          row.subjectCode(),
          row.subjectName(),
          formatPattern(row.schedulePattern()),
          row.blockLabel() == null ? "N/A" : row.blockLabel(),
          row.estimatedMinutes() == null ? "N/A" : row.estimatedMinutes(),
          row.day() == null ? "N/A" : row.day(),
          timeRange,
          row.roomLabel() == null ? "N/A" : row.roomLabel(),
          row.status(),
          row.details()
      });
    }
  }

  private LocalTime parseTime(String value) {
    if (value == null || value.isBlank()) {
      return null;
    }

    try {
      return LocalTime.parse(value.trim(), TIME_FORMATTER);
    } catch (DateTimeParseException ex) {
      return null;
    }
  }

  private String formatPattern(String pattern) {
    if (pattern == null || pattern.isBlank()) {
      return "LECTURE ONLY";
    }

    return pattern.replace('_', ' ');
  }

  private void addField(JPanel panel, JLabel label, java.awt.Component component, int row) {
    GridBagConstraints gbcLabel = new GridBagConstraints();
    gbcLabel.gridx = 0;
    gbcLabel.gridy = row;
    gbcLabel.insets = new Insets(2, 2, 4, 8);
    gbcLabel.anchor = GridBagConstraints.WEST;

    panel.add(label, gbcLabel);

    GridBagConstraints gbcField = new GridBagConstraints();
    gbcField.gridx = 1;
    gbcField.gridy = row;
    gbcField.weightx = 1.0;
    gbcField.fill = GridBagConstraints.HORIZONTAL;
    gbcField.insets = new Insets(2, 0, 6, 2);
    panel.add(component, gbcField);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClose;
  private javax.swing.JButton btnGenerate;
  private javax.swing.JButton btnPreview;
  private javax.swing.JComboBox<String> cbxSectionPeriod;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblSummary;
  private javax.swing.JTable tblPreview;
  private javax.swing.JFormattedTextField txtMaxEndTime;
  private javax.swing.JFormattedTextField txtMinStartTime;
  private com.group5.paul_esys.components.WindowBar windowBar1;
  // End of variables declaration//GEN-END:variables
}
