/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group5.paul_esys.screens.registrar.cards;

/**
 *
 * @author nytri
 */
public class test extends javax.swing.JPanel {

	/**
	 * Creates new form test
	 */
	public test() {
		for (int i = 0; i < 15; i++){
			jPanel3.add(new FacultyMemberCard());
		}
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jPanel3 = new javax.swing.JPanel();
                facultyMemberCard1 = new com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard();
                facultyMemberCard3 = new com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard();
                facultyMemberCard4 = new com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard();
                facultyMemberCard2 = new com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard();
                facultyMemberCard5 = new com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard();

                jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 8));
                jPanel3.add(facultyMemberCard1);
                jPanel3.add(facultyMemberCard3);
                jPanel3.add(facultyMemberCard4);
                jPanel3.add(facultyMemberCard2);
                jPanel3.add(facultyMemberCard5);

                jScrollPane1.setViewportView(jPanel3);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(398, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(125, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(183, 183, 183))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard facultyMemberCard1;
        private com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard facultyMemberCard2;
        private com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard facultyMemberCard3;
        private com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard facultyMemberCard4;
        private com.group5.paul_esys.screens.registrar.cards.FacultyMemberCard facultyMemberCard5;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables
}
