package com.group5.paul_esys.screens.admin;

import com.group5.paul_esys.screens.admin.panels.AdminDashboardPanel;
import com.group5.paul_esys.screens.registrar.panels.RegistrarCurriculumManagement;
import com.group5.paul_esys.screens.registrar.panels.RegistrarDepartmentManagement;
import com.group5.paul_esys.screens.registrar.panels.RegistrarRoomsManagementPanel;
import com.group5.paul_esys.screens.registrar.panels.RegistrarSubjectManagement;

/**
 *
 * @author nytri
 */
public final class AdminDashboard extends javax.swing.JFrame {

	/**
	 * Creates new form AdminDashboard
	 */
	public AdminDashboard() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.initializeFrame();
	}

	public void initializeFrame(){
		this.tabbedPaneAdmin.add("Users", new AdminDashboardPanel());
		this.tabbedPaneAdmin.add("Subjects", new RegistrarSubjectManagement());
		this.tabbedPaneAdmin.add("Curriculum", new RegistrarCurriculumManagement());
		this.tabbedPaneAdmin.add("Rooms", new RegistrarRoomsManagementPanel());
		this.tabbedPaneAdmin.add("Departments", new RegistrarDepartmentManagement());
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                rootPanel = new javax.swing.JPanel();
                tabbedPaneAdmin = new javax.swing.JTabbedPane();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                rootPanel.setBackground(new java.awt.Color(255, 255, 255));

                tabbedPaneAdmin.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
                tabbedPaneAdmin.setTabPlacement(javax.swing.JTabbedPane.LEFT);

                javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
                rootPanel.setLayout(rootPanelLayout);
                rootPanelLayout.setHorizontalGroup(
                        rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabbedPaneAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                );
                rootPanelLayout.setVerticalGroup(
                        rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(tabbedPaneAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel rootPanel;
        private javax.swing.JTabbedPane tabbedPaneAdmin;
        // End of variables declaration//GEN-END:variables
}
