/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group5.paul_esys.screens.admin;

import com.group5.paul_esys.modules.admin.model.Admin;
import com.group5.paul_esys.modules.admin.services.AdminService;
import javax.swing.JOptionPane;

/**
 *
 * @author nytri
 */
public class AdminForm extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminForm.class.getName());
        private final AdminService adminService = AdminService.getInstance();
        private final Admin editingAdmin;
        private final Runnable onSavedCallback;

	/**
	 * Creates new form AdminForm
	 */
	public AdminForm() {
		this(null, null);
	}

        public AdminForm(Admin editingAdmin, Runnable onSavedCallback) {
                this.editingAdmin = editingAdmin;
                this.onSavedCallback = onSavedCallback;
                this.setUndecorated(true);
                initComponents();
                initializeFormState();
		this.setLocationRelativeTo(null);
	}

        private void initializeFormState() {
                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                if (editingAdmin == null) {
                        return;
                }

                jLabel1.setText("Update Admin Account");
                btnSave.setText("Update");
                jLabel6.setText("New Password (Optional)");

                txtFirstName.setText(editingAdmin.getFirstName() == null ? "" : editingAdmin.getFirstName());
                txtLastName.setText(editingAdmin.getLastName() == null ? "" : editingAdmin.getLastName());
                txtContactNumber.setText(editingAdmin.getContactNumber() == null ? "" : editingAdmin.getContactNumber());
                txtEmail.setText(
                        adminService.getUserEmailByUserId(editingAdmin.getUserId()).orElse("")
                );

                txtPassword.setText("");
                txtConfirmPassword.setText("");
        }

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                windowBar1 = new com.group5.paul_esys.components.WindowBar();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                txtFirstName = new javax.swing.JTextField();
                txtLastName = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtContactNumber = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txtEmail = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txtPassword = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                txtConfirmPassword = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                btnSave = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Create Admin Account");

                jLabel2.setText("First Name");

                txtFirstName.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                txtLastName.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel3.setText("Last Name");

                txtContactNumber.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel4.setText("Contact Number");

                txtEmail.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel5.setText("Email");

                txtPassword.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel6.setText("Password");

                txtConfirmPassword.setBorder(new com.group5.paul_esys.ui.TextFieldRoundBorder());

                jLabel7.setText("Confirm Password");

                btnSave.setBackground(new java.awt.Color(119, 0, 0));
                btnSave.setForeground(new java.awt.Color(255, 255, 255));
                btnSave.setText("Save");
                btnSave.addActionListener(this::btnSaveActionPerformed);

                btnCancel.setBackground(new java.awt.Color(119, 0, 0));
                btnCancel.setForeground(new java.awt.Color(255, 255, 255));
                btnCancel.setText("Cancel");
                btnCancel.addActionListener(this::btnCancelActionPerformed);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmail)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtContactNumber)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLastName)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFirstName)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtConfirmPassword))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave)
                                        .addComponent(btnCancel))
                                .addContainerGap(21, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(windowBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(windowBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
                dispose();
        }//GEN-LAST:event_btnCancelActionPerformed

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                saveAdmin();
        }//GEN-LAST:event_btnSaveActionPerformed

        private void saveAdmin() {
                String firstName = normalizeRequiredText(txtFirstName.getText(), "First name");
                if (firstName == null) {
                        return;
                }

                String lastName = normalizeRequiredText(txtLastName.getText(), "Last name");
                if (lastName == null) {
                        return;
                }

                String email = normalizeRequiredText(txtEmail.getText(), "Email");
                if (email == null) {
                        return;
                }

                if (!email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Email format is invalid.",
                                "Validation Error",
                                JOptionPane.WARNING_MESSAGE
                        );
                        return;
                }

                String contactNumber = normalizeOptionalText(txtContactNumber.getText());
                if (contactNumber != null && !contactNumber.matches("^[0-9+\\-\\s()]{7,20}$")) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Contact number format is invalid.",
                                "Validation Error",
                                JOptionPane.WARNING_MESSAGE
                        );
                        return;
                }

                String password = txtPassword.getText().trim();
                String confirmPassword = txtConfirmPassword.getText().trim();

                if (editingAdmin == null && password.isEmpty()) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Password is required for new admin accounts.",
                                "Validation Error",
                                JOptionPane.WARNING_MESSAGE
                        );
                        return;
                }

                if (!password.equals(confirmPassword)) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Password and confirm password do not match.",
                                "Validation Error",
                                JOptionPane.WARNING_MESSAGE
                        );
                        return;
                }

                if (!password.isEmpty() && password.length() < 8) {
                        JOptionPane.showMessageDialog(
                                this,
                                "Password must be at least 8 characters.",
                                "Validation Error",
                                JOptionPane.WARNING_MESSAGE
                        );
                        return;
                }

                if (editingAdmin == null) {
                        Admin admin = new Admin()
                                .setFirstName(firstName)
                                .setLastName(lastName)
                                .setContactNumber(contactNumber);

                        if (adminService.registerAdmin(email, password, admin).isEmpty()) {
                                JOptionPane.showMessageDialog(
                                        this,
                                        "Failed to create admin account.",
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE
                                );
                                return;
                        }

                        JOptionPane.showMessageDialog(
                                this,
                                "Admin account created successfully.",
                                "Success",
                                JOptionPane.INFORMATION_MESSAGE
                        );
                } else {
                        editingAdmin
                                .setFirstName(firstName)
                                .setLastName(lastName)
                                .setContactNumber(contactNumber);

                        boolean updated = adminService.updateAdminWithEmail(editingAdmin, email, password);
                        if (!updated) {
                                JOptionPane.showMessageDialog(
                                        this,
                                        "Failed to update admin account.",
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE
                                );
                                return;
                        }

                        JOptionPane.showMessageDialog(
                                this,
                                "Admin account updated successfully.",
                                "Success",
                                JOptionPane.INFORMATION_MESSAGE
                        );
                }

                if (onSavedCallback != null) {
                        onSavedCallback.run();
                }

                dispose();
        }

        private String normalizeOptionalText(String value) {
                if (value == null) {
                        return null;
                }

                String trimmed = value.trim();
                return trimmed.isEmpty() ? null : trimmed;
        }

        private String normalizeRequiredText(String value, String fieldLabel) {
                String normalized = normalizeOptionalText(value);
                if (normalized != null) {
                        return normalized;
                }

                JOptionPane.showMessageDialog(
                        this,
                        fieldLabel + " is required.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );
                return null;
        }

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new AdminForm().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSave;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField txtConfirmPassword;
        private javax.swing.JTextField txtContactNumber;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtFirstName;
        private javax.swing.JTextField txtLastName;
        private javax.swing.JTextField txtPassword;
        private com.group5.paul_esys.components.WindowBar windowBar1;
        // End of variables declaration//GEN-END:variables
}
