package com.group5.paul_esys.screens.registrar;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTGitHubIJTheme;
import com.group5.paul_esys.modules.registrar.model.Registrar;
import com.group5.paul_esys.modules.users.services.UserSession;
import com.group5.paul_esys.screens.registrar.panels.RegistrarCurriculumManagement;
import com.group5.paul_esys.screens.registrar.panels.RegistrarRoomsManagementPanel;
import com.group5.paul_esys.screens.registrar.panels.RegistrarSubjectManagement;
import com.group5.paul_esys.screens.registrar.panels.StudentManagement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shan
 */
public final class RegistrarDashboard extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPortal
     */
    public RegistrarDashboard() {
        FlatMTGitHubIJTheme.setup();
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);

	// Set yung pangalan ng title
        Registrar registrar = (Registrar) UserSession.getInstance()
            .getUserInformation()
            .getUser();
        String fullName = String.format(
            "%s, %s",
            registrar.getLastName(),
            registrar.getFirstName()
        );
        this.windowBar1.setTitle("Welcome " + fullName);

	// Add nung mga tabs
	tabbedPaneStudents.add("Dashboard", new com.group5.paul_esys.screens.registrar.panels.RegistrarDashboard());
	tabbedPaneStudents.add("Students", new StudentManagement());
    	tabbedPaneStudents.add("Subjects", new RegistrarSubjectManagement());
	tabbedPaneStudents.add("Curriculums", new RegistrarCurriculumManagement());
	tabbedPaneStudents.add("Rooms", new RegistrarRoomsManagementPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                popMenuRegistrarTable = new javax.swing.JPopupMenu();
                mItemRegistrarDelete = new javax.swing.JMenuItem();
                mItemRegistrarUpdate = new javax.swing.JMenuItem();
                tabbedPaneStudents = new javax.swing.JTabbedPane();
                windowBar1 = new com.group5.paul_esys.components.WindowBar();

                mItemRegistrarDelete.setText("Delete Student");
                mItemRegistrarDelete.addActionListener(this::mItemRegistrarDeleteActionPerformed);
                popMenuRegistrarTable.add(mItemRegistrarDelete);

                mItemRegistrarUpdate.setText("Update Student");
                mItemRegistrarUpdate.addActionListener(this::mItemRegistrarUpdateActionPerformed);
                popMenuRegistrarTable.add(mItemRegistrarUpdate);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
                setResizable(false);
                setSize(new java.awt.Dimension(1280, 720));

                tabbedPaneStudents.setBackground(new java.awt.Color(255, 255, 255));
                tabbedPaneStudents.setTabPlacement(javax.swing.JTabbedPane.LEFT);
                tabbedPaneStudents.setMaximumSize(new java.awt.Dimension(1280, 720));
                tabbedPaneStudents.setPreferredSize(new java.awt.Dimension(1280, 720));

                windowBar1.setTitle("Welcome!");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(windowBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(tabbedPaneStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(windowBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(tabbedPaneStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void mItemRegistrarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRegistrarDeleteActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_mItemRegistrarDeleteActionPerformed

        private void mItemRegistrarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRegistrarUpdateActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_mItemRegistrarUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() ->
            new RegistrarDashboard().setVisible(true)
        );
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem mItemRegistrarDelete;
        private javax.swing.JMenuItem mItemRegistrarUpdate;
        private javax.swing.JPopupMenu popMenuRegistrarTable;
        private javax.swing.JTabbedPane tabbedPaneStudents;
        private com.group5.paul_esys.components.WindowBar windowBar1;
        // End of variables declaration//GEN-END:variables
}
