/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group5.paul_esys.screens.faculty;

import com.group5.paul_esys.modules.faculty.model.Faculty;
import com.group5.paul_esys.modules.users.models.user.UserInformation;
import com.group5.paul_esys.modules.users.services.UserSession;
import com.group5.paul_esys.screens.faculty.panels.FacultyDashboardPanel;
import com.group5.paul_esys.screens.registrar.panels.RegistrarSchedulesManagement;
import com.group5.paul_esys.screens.shared.panels.SettingsPanel;

/**
 *
 * @author nytri
 */
public class FacultyDashboard extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultyDashboard.class.getName());

	/**
	 * Creates new form FacultyDashboard
	 */
	public FacultyDashboard() {
		this.setUndecorated(true);
		initComponents();
		this.setLocationRelativeTo(null);

		boolean departmentHead = isCurrentFacultyDepartmentHead();
		tabbedPaneSideBar.add("Dashboard", new FacultyDashboardPanel());
		if (departmentHead) {
			tabbedPaneSideBar.add("Schedule Management", new RegistrarSchedulesManagement());
		}
		tabbedPaneSideBar.add("Security", new SettingsPanel());
		if (departmentHead) {
			windowBar1.setTitle("Faculty Head Dashboard");
		}
	}

	private boolean isCurrentFacultyDepartmentHead() {
		UserInformation<?> userInformation = UserSession.getInstance().getUserInformation();
		if (userInformation == null) {
			return false;
		}

		Object user = userInformation.getUser();
		if (user instanceof Faculty faculty) {
			return faculty.isDepartmentHead();
		}

		return false;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                windowBar1 = new com.group5.paul_esys.components.WindowBar();
                tabbedPaneSideBar = new javax.swing.JTabbedPane();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

                windowBar1.setTitle("Faculty Dashboard");
                getContentPane().add(windowBar1);

                tabbedPaneSideBar.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
                tabbedPaneSideBar.setPreferredSize(new java.awt.Dimension(1280, 720));
                getContentPane().add(tabbedPaneSideBar);

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new FacultyDashboard().setVisible(true));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTabbedPane tabbedPaneSideBar;
        private com.group5.paul_esys.components.WindowBar windowBar1;
        // End of variables declaration//GEN-END:variables
}
